apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: app-new 
  janus-idp.io/tekton: app-new
  backstage.io/kubernetes-id: app-new
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: app-new
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  